#!/bin/bash

export XDG_CONFIG_HOME=$HOME/.config

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/{fish,nix}

ln -sf "$PWD/.bashrc" $HOME/.bashrc
ln -sf "$PWD/.inputrc" $HOME/.inputrc
ln -sf "$PWD/.tmux.conf" $HOME/.tmux.conf

ln -sf "$PWD/config.fish" $XDG_CONFIG_HOME/fish/config.fish
ln -sf "$PWD/nix.conf" "$XDG_CONFIG_HOME/nix/nix.conf"

ln -sf $PWD/starship.toml $XDG_CONFIG_HOME/starship.toml

git clone https://github.com/razzkumar/nvim  $XDG_CONFIG_HOME/nvim

if which nix > /dev/null 2>&1; then
  echo "setting up on nix"
  nix shell
else
  echo "setting up on debian"
  ./install-debian.sh
fi

# install Nix packages from config.nix
