#!/bin/bash

export XDG_CONFIG_HOME=$HOME/.config

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/{nixpkgs,fish}

git clone https://github.com/razzkumar/nvim  $XDG_CONFIG_HOME/nvim

ln -sf "$PWD/" $HOME/.bashrc
ln -sf "$PWD/.inputrc" $HOME/.inputrc
ln -sf "$PWD/.tmux.conf" $HOME/.tmux.conf

ln -sf "$PWD/config.fish" $XDG_CONFIG_HOME/fish/config.fish
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

ln -sf $PWD/starship.toml $XDG_CONFIG_HOME/starship.toml
# install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages

